name: snapping_sheet
description: A new Flutter package project.
version: 0.0.1
author: Adam Jonsson
homepage: https://github.com/AdamJonsson/snapping_sheet

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
