name: snapping_sheet
description: A package that provides a sheet widget that snaps to different vertical positions
version: 2.0.1
homepage: https://github.com/AdamJonsson/snapping_sheet

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
